import { CreateTransactionFormInput } from './common-schema';

export const sampleInitialData: CreateTransactionFormInput = {
  currencyDetails: {
    fx_currency: 'PLN',
    fx_amount: '50000',
    settlement_rate: '75.5',
    add_margin: '500',
    customer_rate: '76',
    declared_education_loan_amount: '500000',
    previous_transaction_amount: '100000',
    declared_previous_amount: '50000',
    total_transaction_amount_tcs: '1500',
    invoiceRateTable: {
      transaction_value: {
        company_rate: '740000',
        agent_mark_up: '500',
        rate: '740500',
      },
      remittance_charges: {
        company_rate: '500',
        agent_mark_up: '50',
        rate: '550',
      },
      nostro_charges: {
        company_rate: '300',
        agent_mark_up: '30',
        rate: '330',
      },
      other_charges: {
        company_rate: '200',
        agent_mark_up: '20',
        rate: '220',
      },
      transaction_amount: {
        rate: '741600',
      },
      gst_amount: {
        rate: '133488',
      },
      total_inr_amount: {
        rate: '875088',
      },
      tcs: {
        rate: '1500',
      },
    },
  },
  beneficiaryDetails: {
    beneficiary_name: 'ASMA',
    beneficiary_address: 'University Road',
    beneficiary_city: 'New York',
    beneficiary_country: 'USA',
    beneficiary_account_number_iban_number: 'US1234567890',
    beneficiary_swift_code: 'ABCDUS33',
    beneficiary_bank_name: 'Bank of America',
    beneficiary_bank_address: 'New York Branch',
    sort_bsb_aba_transit_code: '021000021',
    message_to_beneficiary_additional_information: 'Education fee payment',
    student_name: 'Student One',
    student_passport_number: 'N1234567',
    payment_instruction_number: 'PAYINS001',
    university_name: 'ABC University',
    intermediaryBankDetails: 'no',
    intermediary_bank_account_number: '',
    intermediary_bank_swift_code: '',
    intermediary_bank_name: '',
    intermediary_bank_address: '',
  },
  transactionDetails: {
    company_reference_number: 'COMP-REF-001',
    agent_reference_number: 'AGENT-REF-001',
    purpose: 'Education',
    transaction_purpose_map_id: '1',
    fx_currency: 'USD',
    fx_amount: 10000,
    company_settlement_rate: 75.5,
    add_margin: 500,
    customer_rate: 76,
    nostro_charges: 0,
    applicant_name: 'John Doe',
    applicant_pan_number: 'ABCDE1234F',
    applicant_email: 'john.doe@email.com',
    applicant_mobile_number: '9876543210',
    source_of_funds: 'Self Income',
    paid_by: 'Self',
    payee_name: 'Jane Doe',
    payee_pan_number: 'FGHIJ5678K',
    applicant_id_document: 'Passport',
    passport_number: 'N1234567',
    place_of_issue: 'Chennai',
    applicant_address: '123 Main Street',
    applicant_city: 'Chennai',
    applicant_state: 'Tamil Nadu',
    applicant_country: 'India',
    postal_code: '600001',
  },
};
