export const beneficiaryDetailsMeta = [
  {
    name: 'beneficiaryName',
    label: 'Beneficiary Name',
    type: 'text',
    placeholder: 'Enter Beneficiary Name',
    required: false,
  },
  {
    name: 'beneficiaryAddress',
    label: 'Beneficiary Address',
    type: 'text',
    placeholder: 'Enter Beneficiary Address',
    required: false,
  },
  {
    name: 'beneficiaryCity',
    label: 'Beneficiary City',
    type: 'text',
    placeholder: 'Enter Beneficiary City',
    required: false,
  },
  {
    name: 'beneficiaryCountry',
    label: 'Beneficiary Country',
    type: 'text',
    placeholder: 'Enter Beneficiary Country',
    required: false,
  },
  {
    name: 'beneficiaryAccountNumberIBANNumber',
    label: 'Beneficiary Account Number / IBAN Number',
    type: 'text',
    placeholder: 'Enter Beneficiary Account Number / IBAN Number',
    required: false,
  },
  {
    name: 'beneficiarySwiftCode',
    label: 'Beneficiary Swift Code',
    type: 'text',
    placeholder: 'Enter Beneficiary Swift Code',
    required: false,
  },
  {
    name: 'beneficiaryBankName',
    label: 'Beneficiary Bank Name',
    type: 'text',
    placeholder: 'Enter Beneficiary Bank Name',
    required: false,
  },
  {
    name: 'beneficiaryBankAddress',
    label: 'Beneficiary Bank Address',
    type: 'text',
    placeholder: 'Enter Beneficiary Bank Address',
    required: false,
  },
  {
    name: 'sortBsbAbaTransitCode',
    label: 'Sort/BSB/ABA Transit Code',
    type: 'text',
    placeholder: 'Enter Sort/BSB/ABA Transit Code',
    required: false,
  },
  {
    name: 'nostroCharges',
    label: 'Nostro Charges',
    type: 'text',
    placeholder: 'Enter Nostro Charges',
    required: false,
  },
  {
    name: 'messageToBeneficaryAdditionalInformation',
    label: 'Message to Beneficiary / Additional Information',
    type: 'text',
    placeholder: 'Enter Message to Beneficiary / Additional Information',
    required: false,
  },
  {
    name: 'studentName',
    label: 'Student Name',
    type: 'text',
    placeholder: 'Enter Student Name',
    required: false,
  },
  {
    name: 'StudentPassportNumber',
    label: 'Student Passport Number',
    type: 'text',
    placeholder: 'Enter Student Passport Number',
    required: false,
  },
  {
    name: 'paymentIndtructionNumber',
    label: 'Payment Instruction Number',
    type: 'text',
    placeholder: 'Enter Payment Instruction Number',
    required: false,
  },
  {
    name: 'universityName',
    label: 'University Name',
    type: 'text',
    placeholder: 'Enter University Name',
    required: false,
  },
];

// Intermediary Bank Details
export const beneficiaryBank = [
  {
    name: 'intermediaryBankAccountNumber',
    label: 'Intermediary Bank Account Number',
    type: 'text',
    placeholder: 'Enter Intermediary Bank Account Number',
    required: false,
  },
  {
    name: 'intermediaryBankSwiftCode',
    label: 'Intermediary Bank Swift Code',
    type: 'text',
    placeholder: 'Enter Intermediary Bank Swift Code',
    required: false,
  },
  {
    name: 'intermediaryBankName',
    label: 'Intermediary Bank Name',
    type: 'text',
    placeholder: 'Enter Intermediary Bank Name',
    required: false,
  },
  {
    name: 'intermediaryBankAddress',
    label: 'Intermediary Bank Address',
    type: 'text',
    placeholder: 'Enter Intermediary Bank Address',
    required: false,
  },
];
