const transactionBasicDetailsMeta = [
  {
    name: 'niumRefrenceNumber',
    label: 'Nium Reference Number',
    type: 'text',
    placeholder: 'Enter Nium Reference Number',
    required: false,
  },
  {
    name: 'agentRefrenceNumber',
    label: 'Agent Reference Number',
    type: 'text',
    placeholder: 'Enter Agent Reference Number',
    required: false,
  },
  {
    name: 'createdDate',
    label: 'Created Date',
    type: 'date',
    placeholder: 'Select Created Date',
    required: false,
  },
  {
    name: 'dealExpiry',
    label: 'Deal Expiry',
    type: 'date',
    placeholder: 'Select Deal Expiry Date',
    required: false,
  },
  {
    name: 'transactioType',
    label: 'Transaction Type',
    type: 'text',
    placeholder: 'Enter Transaction Type',
    required: false,
  },
  {
    name: 'purpose',
    label: 'Purpose',
    type: 'text',
    placeholder: 'Enter Purpose',
    required: false,
  },
  {
    name: 'fxCurrency',
    label: 'FX Currency',
    type: 'text',
    placeholder: 'Enter FX Currency',
    required: false,
  },
  {
    name: 'fxAmount',
    label: 'FX Amount',
    type: 'number',
    placeholder: 'Enter FX Amount',
    required: false,
  },
  {
    name: 'settlementRate',
    label: 'Settlement Rate',
    type: 'number',
    placeholder: 'Enter Settlement Rate',
    required: false,
  },
  {
    name: 'billingRate',
    label: 'Billing Rate',
    type: 'number',
    placeholder: 'Enter Billing Rate',
    required: false,
  },
  {
    name: 'applicantName',
    label: 'Applicant Name',
    type: 'text',
    placeholder: 'Enter Applicant Name',
    required: false,
  },
  {
    name: 'applicantPanNumber',
    label: 'Applicant PAN Number',
    type: 'text',
    placeholder: 'Enter Applicant PAN Number',
    required: false,
  },
  {
    name: 'applicantDOB',
    label: 'Applicant Date of Birth',
    type: 'date',
    placeholder: 'Select Applicant DOB',
    required: false,
  },
  {
    name: 'applicantEmail',
    label: 'Applicant Email',
    type: 'email',
    placeholder: 'Enter Applicant Email',
    required: false,
  },
  {
    name: 'applicantMobileNumber',
    label: 'Applicant Mobile Number',
    type: 'phone',
    placeholder: 'Enter Applicant Mobile Number',
    required: false,
  },
  {
    name: 'sourceOfFunds',
    label: 'Source of Funds',
    type: 'text',
    placeholder: 'Enter Source of Funds',
    required: false,
  },
  {
    name: 'paidBy',
    label: 'Paid By',
    type: 'text',
    placeholder: 'Enter Paid By',
    required: false,
  },
  {
    name: 'payeeName',
    label: 'Payee Name',
    type: 'text',
    placeholder: 'Enter Payee Name',
    required: false,
  },
  {
    name: 'payeePanNumber',
    label: 'Payee PAN Number',
    type: 'text',
    placeholder: 'Enter Payee PAN Number',
    required: false,
  },
  {
    name: 'payeeDOB',
    label: 'Payee Date of Birth',
    type: 'date',
    placeholder: 'Select Payee DOB',
    required: false,
  },
  {
    name: 'applicantIdDocument',
    label: 'Applicant ID Document',
    type: 'text',
    placeholder: 'Enter Applicant ID Document',
    required: false,
  },
  {
    name: 'passportNumber',
    label: 'Passport Number',
    type: 'text',
    placeholder: 'Enter Passport Number',
    required: false,
  },
  {
    name: 'passportIssuedDate',
    label: 'Passport Issued Date',
    type: 'date',
    placeholder: 'Select Passport Issued Date',
    required: false,
  },
  {
    name: 'passportExpiryDate',
    label: 'Passport Expiry Date',
    type: 'date',
    placeholder: 'Select Passport Expiry Date',
    required: false,
  },
  {
    name: 'placeOfIssue',
    label: 'Place of Issue',
    type: 'text',
    placeholder: 'Enter Place of Issue',
    required: false,
  },
  {
    name: 'applicantAddress',
    label: 'Applicant Address',
    type: 'text',
    placeholder: 'Enter Applicant Address',
    required: false,
  },
  {
    name: 'applicantCity',
    label: 'Applicant City',
    type: 'text',
    placeholder: 'Enter Applicant City',
    required: false,
  },
  {
    name: 'applicantState',
    label: 'Applicant State',
    type: 'text',
    placeholder: 'Enter Applicant State',
    required: false,
  },
  {
    name: 'applicantCountry',
    label: 'Applicant Country',
    type: 'text',
    placeholder: 'Enter Applicant Country',
    required: false,
  },
  {
    name: 'postalCode',
    label: 'Postal Code',
    type: 'text',
    placeholder: 'Enter Postal Code',
    required: false,
  },
];

export default transactionBasicDetailsMeta;
