export const beneficiaryDetailsConfig = [
  {
    name: 'beneficiary_name',
    label: 'Beneficiary Name',
    type: 'text',
    placeholder: 'Enter Beneficiary Name',
    required: true,
  },
  {
    name: 'beneficiary_address',
    label: 'Beneficiary Address',
    type: 'text',
    placeholder: 'Enter Beneficiary Address',
    required: true,
  },
  {
    name: 'beneficiary_city',
    label: 'Beneficiary City',
    type: 'text',
    placeholder: 'Enter Beneficiary City',
    required: true,
  },
  {
    name: 'beneficiary_country',
    label: 'Beneficiary Country',
    type: 'text',
    placeholder: 'Enter Beneficiary Country',
    required: true,
  },
  {
    name: 'beneficiary_account_number_iban_number',
    label: 'Beneficiary Account Number / IBAN Number',
    type: 'text',
    placeholder: 'Enter Beneficiary Account Number / IBAN Number',
    required: true,
  },
  {
    name: 'beneficiary_swift_code',
    label: 'Beneficiary Swift Code',
    type: 'text',
    placeholder: 'Enter Beneficiary Swift Code',
    required: true,
  },
  {
    name: 'beneficiary_bank_name',
    label: 'Beneficiary Bank Name',
    type: 'text',
    placeholder: 'Enter Beneficiary Bank Name',
    required: true,
  },
  {
    name: 'beneficiary_bank_address',
    label: 'Beneficiary Bank Address',
    type: 'text',
    placeholder: 'Enter Beneficiary Bank Address',
    required: true,
  },
  {
    name: 'sort_bsb_aba_transit_code',
    label: 'SORT/BSB/ABA/TRANSIT Code',
    type: 'text',
    placeholder: 'Enter SORT/BSB/ABA/TRANSIT Code',
    required: true,
  },
  {
    name: 'message_to_beneficiary_additional_information',
    label: 'Message to Beneficiary / Additional Information',
    type: 'text',
    placeholder: 'Enter Message to Beneficiary / Additional Information',
    required: true,
  },
  {
    name: 'student_name',
    label: 'Student Name',
    type: 'text',
    placeholder: 'Enter Student Name',
    required: false,
  },
  {
    name: 'student_passport_number',
    label: 'Student Passport Number',
    type: 'text',
    placeholder: 'Enter Student Passport Number',
    required: false,
  },
  {
    name: 'payment_instruction_number',
    label: 'Payment Instruction Number',
    type: 'text',
    placeholder: 'Enter Payment Instruction Number',
    required: false,
  },
  {
    name: 'university_name',
    label: 'University Name',
    type: 'text',
    placeholder: 'Enter University Name',
    required: false,
  },
];

// Intermediary Bank Details
export const beneficiaryBank = [
  {
    name: 'intermediary_bank_account_number',
    label: 'Intermediary Bank Account No',
    type: 'text',
    placeholder: 'Enter Intermediary Bank Account No',
    required: false,
  },
  {
    name: 'intermediary_bank_swift_code',
    label: 'Intermediary Bank Swift Code',
    type: 'text',
    placeholder: 'Enter Intermediary Bank Swift Code',
    required: false,
  },
  {
    name: 'intermediary_bank_name',
    label: 'Intermediary Bank Name',
    type: 'text',
    placeholder: 'Enter Intermediary Bank Name',
    required: false,
  },
  {
    name: 'intermediary_bank_address',
    label: 'Intermediary Bank Address',
    type: 'text',
    placeholder: 'Enter Intermediary Bank Address',
    required: false,
  },
];
