export interface TransactionData {
  id: string;
  temp_id: string;
  deal_code: string | null;
  transaction_type: string;
  currency_code: string;
  deal_amount: string;
  margin_amount: string;
  settlement_rate: string;
  customer_rate: string;
  booking_status: string;
  created_by: string;
  approved_by: string | null;
  approved_at: string | null;
  rejection_reason: string | null;
  created_at: string;
  updated_at: string;
  transactions: unknown[];
  payment_records: unknown[];
}

export interface DealsResponseTransaction {
  id: string;
  transaction_id: string;
  deal_booking_id: string;
  fx_amount: string;
  fx_currency: string;
  transaction_amount: string;
  total_payable_amount: string;
  beneficiary_amount: string;
  remittance_charges: string;
  other_charges: string;
  total_gst_amount: string;
  total_inr_amount: string;
  tcs: string | null;
  nostro_charges_type: string | null;
  nostro_charges_amount: string;
  transaction_status: string;
  kyc_status: string;
  valuation_date: string;
  purpose: string;
  source_of_funds: string;
  created_at: string;
  updated_at: string;
  agent_ref_number: string;
  company_ref_number: string;
  order_expiry: string;
  order_date: string;
  transaction_purpose_map_id: string;
  agent_markup_remittance_charges: string;
  agent_markup_nostro_charges: string;
  agent_markup_other_charges: string;
  swift_copy: string | null;
  kyc_details: {
    id: string;
    transaction_id: string;
    applicant_name: string;
    applicant_email: string;
    applicant_address: string;
    applicant_city: string;
    applicant_state: string;
    applicant_country: string;
    postal_code: string;
    beneficiary_address: string;
    beneficiary_city: string;
    beneficiary_country: string;
    beneficiary_account_number: string;
    beneficiary_swift_code: string;
    beneficiary_bank_name: string;
    beneficiary_bank_address: string;
    sort_bsb_aba_transit_code: string;
    message_to_beneficiary: string;
    student_name: string | null;
    student_passport_number: string | null;
    university_name: string | null;
    applicant_mobile: string;
    applicant_pan: string;
    applicant_dob: string | null;
    payee_name: string;
    passport_number: string;
    place_of_issue: string | null;
    payee_pan: string | null;
    payee_dob: string | null;
    declared_education_loan_amount: string;
    previous_transaction_amount: string;
    declared_previous_amount: string;
    total_transaction_amount_tcs: string;
    paid_by: string | null;
    created_at: string;
    updated_at: string;
    passport_issue_date: string;
    passport_expiry_date: string;
  };
}

export interface DealsResponse {
  id: string;
  temp_id: string;
  deal_code: string | null;
  transaction_type: string;
  currency_code: string;
  deal_amount: string;
  margin_amount: string;
  settlement_rate: string;
  customer_rate: string;
  booking_status: string;
  created_by: string;
  approved_by: string | null;
  approved_at: string | null;
  rejection_reason: string | null;
  created_at: string;
  updated_at: string;
  transactions: DealsResponseTransaction[];
  payment_records: {
    id: string;
    deal_booking_id: string;
    payment_method: string;
    payment_reference: string;
    amount: string;
    payment_status: string;
    upi_id: string;
    qr_code_data: string | null;
    bank_name: string;
    branch_name: string | null;
    challan_number: string | null;
    challan_date: string | null;
    verified_by: string | null;
    verified_at: string | null;
    payment_gateway_response: string | null;
    created_at: string;
    updated_at: string;
    payment_challan_url: string | null;
  }[];
}
