import { FieldType } from '@/types/enums';

const transactionBasicDetailsConfig = [
  {
    name: 'company_reference_number',
    label: 'Company Reference Number',
    type: FieldType.Text,
    placeholder: 'Enter Company Reference Number',
    required: false,
  },
  {
    name: 'agent_reference_number',
    label: 'Agent Reference Number',
    type: FieldType.Text,
    placeholder: 'Enter Agent Reference Number',
    required: false,
  },
  {
    name: 'purpose',
    label: 'Purpose',
    type: FieldType.Select,
    placeholder: 'Enter Purpose',
    required: true,
  },
  {
    name: 'transaction_purpose_map_id',
    label: '',
    type: FieldType.Text,
    placeholder: '',
    required: false,
  },
  {
    name: 'fx_currency',
    label: 'FX Currency',
    type: FieldType.Select,
    placeholder: 'Select FX Currency',
    required: false,
  },
  {
    name: 'fx_amount',
    label: 'FX Amount',
    type: FieldType.Number,
    placeholder: 'Enter FX Amount',
    required: false,
  },
  {
    name: 'company_settlement_rate',
    label: 'Company Settlement Rate',
    type: FieldType.Number,
    placeholder: 'Enter Company Settlement Rate',
    required: false,
  },
  {
    name: 'add_margin',
    label: 'Add Margin',
    type: FieldType.Number,
    placeholder: 'Enter Add Margin',
    required: false,
  },
  {
    name: 'customer_rate',
    label: 'Customer Rate',
    type: FieldType.Number,
    placeholder: 'Enter Customer Rate',
    required: false,
  },
  {
    name: 'nostro_charges',
    label: 'Nostro Charges',
    type: FieldType.Number,
    placeholder: 'Enter Nostro Charges',
    required: false,
  },
  {
    name: 'applicant_name',
    label: 'Applicant Name',
    type: FieldType.Text,
    placeholder: 'Enter Applicant Name',
    required: false,
  },
  {
    name: 'applicant_pan_number',
    label: 'Applicant PAN Number',
    type: FieldType.Text,
    placeholder: 'Enter Applicant PAN Number',
    required: false,
  },
  {
    name: 'applicant_dob',
    label: 'Applicant DOB',
    type: FieldType.Date,
    placeholder: 'Select Applicant DOB',
    required: false,
  },
  {
    name: 'applicant_email',
    label: 'Applicant Email',
    type: FieldType.Email,
    placeholder: 'Enter Applicant Email',
    required: false,
  },
  {
    name: 'applicant_mobile_number',
    label: 'Applicant Mobile Number',
    type: FieldType.Phone,
    placeholder: 'Enter Applicant Mobile Number',
    required: false,
  },
  {
    name: 'source_of_funds',
    label: 'Source of Funds',
    type: FieldType.Select,
    required: false,
    placeholder: 'Select Source of Funds',
    options: {
      self: { label: 'Self' },
      others: { label: 'Others' },
    },
  },
  {
    name: 'paid_by',
    label: 'Paid By',
    type: FieldType.Select,
    required: false,
    placeholder: 'Select Payment Method',
    options: {
      father: { label: 'Father' },
      mother: { label: 'Mother' },
      husband: { label: 'Husband' },
      wife: { label: 'Wife' },
      sister: { label: 'Sister' },
      brother: { label: 'Brother' },
    },
  },
  {
    name: 'payee_name',
    label: 'Payee Name As Per PAN',
    type: FieldType.Text,
    placeholder: 'Enter Payee Name As Per PAN',
    required: false,
  },
  {
    name: 'payee_pan_number',
    label: 'Payee PAN Number',
    type: FieldType.Text,
    placeholder: 'Enter Payee PAN Number',
    required: false,
  },
  {
    name: 'payee_dob',
    label: 'Payee DOB As Per PAN',
    type: FieldType.Date,
    placeholder: 'Select Payee DOB As Per PAN',
    required: false,
  },
  {
    name: 'applicant_id_document',
    label: 'Applicant ID Document',
    type: FieldType.Text,
    placeholder: 'Enter Applicant ID Document',
    required: false,
  },
  {
    name: 'passport_number',
    label: 'Passport Number',
    type: FieldType.Text,
    placeholder: 'Enter Passport Number',
    required: true,
  },
  {
    name: 'passport_issued_date',
    label: 'Passport Issued Date',
    type: FieldType.Date,
    placeholder: 'Select Passport Issued Date',
    required: false,
  },
  {
    name: 'passport_expiry_date',
    label: 'Passport Expiry Date',
    type: FieldType.Date,
    placeholder: 'Select Passport Expiry Date',
    required: false,
  },
  {
    name: 'place_of_issue',
    label: 'Place of Issue',
    type: FieldType.Text,
    placeholder: 'Enter Place of Issue',
    required: false,
  },
  {
    name: 'applicant_address',
    label: 'Applicant Address',
    type: FieldType.Text,
    placeholder: 'Enter Applicant Address',
    required: true,
  },
  {
    name: 'applicant_city',
    label: 'Applicant City',
    type: FieldType.Text,
    placeholder: 'Enter Applicant City',
    required: true,
  },
  {
    name: 'applicant_state',
    label: 'Applicant State',
    type: FieldType.Text,
    placeholder: 'Enter Applicant State',
    required: true,
  },
  {
    name: 'applicant_country',
    label: 'Applicant Country',
    type: FieldType.Text,
    placeholder: 'Enter Applicant Country',
    required: true,
  },
  {
    name: 'postal_code',
    label: 'Postal Code',
    type: FieldType.Number,
    placeholder: 'Enter Postal Code',
    required: true,
  },
];

export default transactionBasicDetailsConfig;
