import { FieldType } from "@/types/enums";

const transactionBasicDetailsConfig = [
  {
    name: 'company_reference_number',
    label: 'Company Reference Number',
    type: FieldType.Text,
    placeholder: 'Enter Company Reference Number',
    required: false,
  },
  {
    name: 'agent_reference_number',
    label: 'Agent Reference Number',
    type: FieldType.Text,
    placeholder: 'Enter Agent Reference Number',
    required: false,
  },
  {
    name: 'created_date',
    label: 'Created Date',
    type: FieldType.Date,
    placeholder: 'Select Created Date',
    required: false,
  },
  {
    name: 'deal_expiry',
    label: 'Deal Expiry',
    type: FieldType.Date,
    placeholder: 'Select Deal Expiry Date',
    required: false,
  },
  {
    name: 'transaction_type',
    label: 'Transaction Type',
    type: FieldType.Text,
    placeholder: 'Enter Transaction Type',
    required: false,
  },
  {
    name: 'purpose',
    label: 'Purpose',
    type: FieldType.Text,
    placeholder: 'Enter Purpose',
    required: false,
  },
  {
    name: 'fx_currency',
    label: 'FX Currency',
    type: FieldType.Text,
    placeholder: 'Enter FX Currency',
    required: false,
  },
  {
    name: 'fx_amount',
    label: 'FX Amount',
    type: FieldType.Number,
    placeholder: 'Enter FX Amount',
    required: false,
  },
  {
    name: 'settlement_rate',
    label: 'Settlement Rate',
    type: FieldType.Number,
    placeholder: 'Enter Settlement Rate',
    required: false,
  },
  {
    name: 'billing_rate',
    label: 'Billing Rate',
    type: FieldType.Number,
    placeholder: 'Enter Billing Rate',
    required: false,
  },
  {
    name: 'applicant_name',
    label: 'Applicant Name',
    type: FieldType.Text,
    placeholder: 'Enter Applicant Name',
    required: false,
  },
  {
    name: 'applicant_pan_number',
    label: 'Applicant PAN Number',
    type: FieldType.Text,
    placeholder: 'Enter Applicant PAN Number',
    required: false,
  },
  {
    name: 'applicant_dob',
    label: 'Applicant Date of Birth',
    type: FieldType.Date,
    placeholder: 'Select Applicant DOB',
    required: false,
  },
  {
    name: 'applicant_email',
    label: 'Applicant Email',
    type: FieldType.Email,
    placeholder: 'Enter Applicant Email',
    required: false,
  },
  {
    name: 'applicant_mobile_number',
    label: 'Applicant Mobile Number',
    type: FieldType.Phone,
    placeholder: 'Enter Applicant Mobile Number',
    required: false,
  },
  {
    name: 'source_of_funds',
    label: 'Source of Funds',
    type: FieldType.Text,
    placeholder: 'Enter Source of Funds',
    required: false,
  },
  {
    name: 'paid_by',
    label: 'Paid By',
    type: FieldType.Text,
    placeholder: 'Enter Paid By',
    required: false,
  },
  {
    name: 'payee_name',
    label: 'Payee Name',
    type: FieldType.Text,
    placeholder: 'Enter Payee Name',
    required: false,
  },
  {
    name: 'payee_pan_number',
    label: 'Payee PAN Number',
    type: FieldType.Text,
    placeholder: 'Enter Payee PAN Number',
    required: false,
  },
  {
    name: 'payee_dob',
    label: 'Payee Date of Birth',
    type: FieldType.Date,
    placeholder: 'Select Payee DOB',
    required: false,
  },
  {
    name: 'applicant_id_document',
    label: 'Applicant ID Document',
    type: FieldType.Text,
    placeholder: 'Enter Applicant ID Document',
    required: false,
  },
  {
    name: 'passport_number',
    label: 'Passport Number',
    type: FieldType.Text,
    placeholder: 'Enter Passport Number',
    required: false,
  },
  {
    name: 'passport_issued_date',
    label: 'Passport Issued Date',
    type: FieldType.Date,
    placeholder: 'Select Passport Issued Date',
    required: false,
  },
  {
    name: 'passport_expiry_date',
    label: 'Passport Expiry Date',
    type: FieldType.Date,
    placeholder: 'Select Passport Expiry Date',
    required: false,
  },
  {
    name: 'place_of_issue',
    label: 'Place of Issue',
    type: FieldType.Text,
    placeholder: 'Enter Place of Issue',
    required: false,
  },
  {
    name: 'applicant_address',
    label: 'Applicant Address',
    type: FieldType.Text,
    placeholder: 'Enter Applicant Address',
    required: false,
  },
  {
    name: 'applicant_city',
    label: 'Applicant City',
    type: FieldType.Text,
    placeholder: 'Enter Applicant City',
    required: false,
  },
  {
    name: 'applicant_state',
    label: 'Applicant State',
    type: FieldType.Text,
    placeholder: 'Enter Applicant State',
    required: false,
  },
  {
    name: 'applicant_country',
    label: 'Applicant Country',
    type: FieldType.Text,
    placeholder: 'Enter Applicant Country',
    required: false,
  },
  {
    name: 'postal_code',
    label: 'Postal Code',
    type: FieldType.Text,
    placeholder: 'Enter Postal Code',
    required: false,
  }
];

export default transactionBasicDetailsConfig;
