import { z } from 'zod';
import { agentAdminCreationSchema } from './agent-admin-creation.schema';

export const agentAdminCreationDefaults: z.input<typeof agentAdminCreationSchema> = {
  agent_name: '',
  emailId: '',
  phoneNo: '',
  agentType: '',
  agentBranchCity: '',
  agentHOBranchState: '',
  entity_name:'',
  pan_no:'',
  date_of_incorporation:'',
  rm_name: '',
  rm_branch_name: '',
  systemCode: '',
  status: 'Active',
  monthlyCreditLimit: '',
  totalCreditDays: '',
  gstClassification: '',
  gstNumber: '',
  gstPhoneNo: '',
  flatDoorNumber: '',
  roadStreet: '',
  areaLocality: '',
  gstCity: '',
  gstState: '',
  pinCode: '',
  gstBranch: '',
  financeSpocName: '',
  financeSpocEmail: '',
  financeSpocPhoneNo: '',
  agent_category: "CNC",
  password:'',
  confirmPassword:'',
  bankAccounts: [
    {
      bankName: 'Bank of Example',
      branchName: 'Main Branch',
      accountHolder: 'John Doe',
      accountNumber: '123456789012',
      ifscCode: 'EXAM0001234',
    },
  ],
  productPurpose: {
    addOnForexMargin: 'No',
    addOnNostroMargin: 'No',
    addOnTTMargin: 'No',
    addOnOtherChargersMargin: 'No',
    esignDocumentDownload: 'No',
    vkycDocumentDownload: 'No',
    chooseProductType: { card: false, currency: false, remittance: true, referral: false },
    purposeTypesForCard: {
      personaltravel: true,
      businesstravel: false,
      education: false,
      immigration: false,
      employment: false,
      medical: false,
    },
  },
  commission_details: {
    commission_product_type: 'Remittance',
    commission_type: 'HYBRID',
    product_margin: {
      agent_fixed_margin: 'PERCENTAGE',
      all_currency: 'SPECIFIC',
      all_currency_margin: 0,
      currency_list: {
        USD: '',
        EUR: '',
        GBP: '',
        CAD: '',
        AUD: '',
        JPY: '',
        SGD: '',
        CHF: '',
        AED: '',
        THB: '',
        NZD: '',
        SAR: '',
        ZAR: '',
      },
    },
    nostro_charges: {
      type: 'FX',
      all_currency: 'SPECIFIC',
      all_currency_margin: 0,
      currency_list: {
        USD: '',
        EUR: '',
        GBP: '',
        CAD: '',
        AUD: '',
        JPY: '',
        SGD: '',
        CHF: '',
        AED: '',
        THB: '',
        NZD: '',
        SAR: '',
        ZAR: '',
      },
    },
    tt_charges: {
      rate: 99.5,
    },
    other_charges: {
      rate: 49,
    },
  },
  agreementValid: '',
  rbiLicenseCategory: '',
  rbiLicenseValidity: '',
  noOfBranches: '',
  extensionMonth: '',
  agreementCopy: '',
  rbiLicenseCopy: '',
};
