import { z } from 'zod';
import { agentAdminCreationSchema } from './agent-admin-creation.schema';

export const agentAdminCreationDefaults: z.input<typeof agentAdminCreationSchema> = {
  agent_code: '',
  agent_name: '',
  emailId: '',
  phoneNo: '',
  agentType: '',
  agentBranchCity: '',
  agentHOBranchState: '',
  ebixRMName: '',
  ebixRMBranchName: '',
  systemCode: '',
  status: 'Active',
  monthlyCreditLimit: '',
  totalCreditDays: '',
  gstClassification: '',
  gstNumber: '',
  gstPhoneNo: '',
  flatDoorNumber: '',
  roadStreet: '',
  areaLocality: '',
  gstCity: '',
  gstState: '',
  pinCode: '',
  gstBranch: '',
  financeSpocName: '',
  financeSpocEmail: '',
  financeSpocPhoneNo: '',
  bankAccounts: [
    {
      bankName: 'Bank of Example',
      branchName: 'Main Branch',
      accountHolder: 'John Doe',
      accountNumber: '123456789012',
      ifscCode: 'EXAM0001234',
    },
  ],
  productPurpose: {
    addOnForexMargin: "No",
    addOnNostroMargin: "No",
    addOnTTMargin: "No",
    addOnOtherChargersMargin: "No",
    esignDocumentDownload: 'No',
    vkycDocumentDownload: 'No',
    chooseProductType: { card: false, currency: false, remittance: true, referral: false },
    creditType: { CNC: true, linecredit: false },
    purposeTypesForCard: { personaltravel: true, businesstravel: false, education: false, immigration: false, employment: false, medical: false },
  },
  commission_details: {
    commission_product_type: 'Remittance',
    commission_type: 'HYBRID',
    product_margin: {
      agent_fixed_margin: 'PERCENTAGE',
      all_currency: 'ALL_CURRENCY',
      all_currency_margin: 0,
      currency_list: {
        USD: "",
        EUR: "",
        GBP: "",
        CAD: "",
        AUD: "",
        JPY: "",
        SGD: "",
        CHF: "",
        AED: "",
        THB: "",
        NZD: "",
        SAR: "",
        ZAR: "",
      },
    },
    nostro_charges: {
      type: 'FX',
      all_currency: 'ALL_CURRENCY',
      all_currency_margin: 0,
      currency_list: {
        USD: "",
        EUR: "",
        GBP: "",
        CAD: "",
        AUD: "",
        JPY: "",
        SGD: "",
        CHF: "",
        AED: "",
        THB: "",
        NZD: "",
        SAR: "",
        ZAR: "",
      },
    },
    tt_charges: {
      rate: 99.5,
    },
    other_charges: {
      rate: 49,
    },
  },
  agreementValid: '2025-10-03T18:30:00.000Z',
  rbiLicenseCategory: 'ADI-VD',
  rbiLicenseValidity: '2025-10-03T18:30:00.000Z',
  noOfBranches: '10',
  extensionMonth: "1",
  agreementCopy:"",
  rbiLicenseCopy:"",
};