import { z } from 'zod';
import { agentAdminCreationSchema } from './agent-admin-creation.schema';

export const agentAdminCreationDefaults: z.input<typeof agentAdminCreationSchema> = {
  vendorCode: 'V001',
  fullName: 'John Doe',
  emailId: 'john.doe@example.com',
  phoneNo: '1234567890',
  agentType: 'Type A',
  agentBranchCity: 'Mumbai',
  agentHOBranchState: 'Maharashtra',
  ebixRMName: 'RM Name',
  ebixRMBranchName: 'Branch Name',
  systemCode: 'SYS001',
  status: 'Active',
  monthlyCreditLimit: '10000',
  totalCreditDays: '30',
  gstClassification: 'Regular',
  gstNumber: '22AAAAA0000A1Z5',
  gstPhoneNo: '9876543210',
  flatDoorNumber: '123',
  roadStreet: 'Main Street',
  areaLocality: 'Locality',
  gstCity: 'Mumbai',
  gstState: 'Maharashtra',
  pinCode: '400001',
  gstBranch: 'Main Branch',
  financeSpocName: 'Finance SPOC',
  financeSpocEmail: 'finance@example.com',
  financeSpocPhoneNo: '1234567890',
  bankAccounts: [
    {
      bankName: 'Bank of Example',
      branchName: 'Main Branch',
      accountHolder: 'John Doe',
      accountNumber: '123456789012',
      ifscCode: 'EXAM0001234',
    },
  ],
  productPurpose: {
    addOnMargin: 'No',
    esignDocumentDownload: 'No',
    vkycDocumentDownload: 'No',
    chooseProductType: { card: false, currency: false, remittance: true, referral: false },
    creditType: { CNC: true, linecredit: false },
    purposeTypesForCard: { personaltravel: true, businesstravel: false, education: false, immigration: false, employment: false, medical: false },
  },
  rateMargin: {
    currency: {
      EUR: { buy: 0.12, sell: 0.2 },
      GBP: { buy: 0.13, sell: 0.22 },
      USD: { buy: 0.1, sell: 0.18 },
    },
    card: {
      markupFlat: 0.25,
      markupPercent: 1.1,
    },
    remittance: {
      slabs: [
        { min: 0, max: 1000, margin: 0.2 },
        { min: 1000, max: 5000, margin: 0.15 },
        { min: 5000, max: 10000, margin: 0.12 },
      ],
    },
  },
  commission_details: {
    commission_product_type: 'Remittance',
    commission_type: 'HYBRID',
    product_margin: {
      agent_fixed_margin: 'PERCENTAGE',
      all_currency: 'ALL_CURRENCY',
      all_currency_margin: 0,
      currency_list: {
        USD: 0.8,
        EUR: 0.7,
        GBP: 0.65,
        CAD: 0.6,
        AUD: 0.55,
        JPY: 0.5,
        SGD: 0.45,
        CHF: 0.4,
        AED: 0.35,
        THB: 0.3,
        NZD: 0.25,
        SAR: 0.2,
        ZAR: 0.15,
      },
    },
    nostro_charges: {
      type: 'FX',
      all_currency: 'ALL_CURRENCY',
      all_currency_margin: 0,
      currency_list: {
        USD: 175,
        EUR: 160,
        GBP: 155,
        CAD: 150,
        AUD: 145,
        JPY: 140,
        SGD: 135,
        CHF: 130,
        AED: 125,
        THB: 120,
        NZD: 115,
        SAR: 110,
        ZAR: 100,
      },
    },
    tt_charges: {
      rate: 99.5,
    },
    other_charges: {
      rate: 49,
    },
  },
  agreementValid: '2025-10-03T18:30:00.000Z',
  rbiLicenseCategory: 'ADI-VD',
  rbiLicenseValidity: '2025-10-03T18:30:00.000Z',
  noOfBranches: '10',
  extensionMonth: "1",
  corporateOnboarding: {
    enabled: true,
    kyc: {
      pan: true,
      gst: true,
      cin: false,
    },
    limits: {
      maxTransaction: 10000,
      dailyLimit: 5000,
    },
    allowedIndustries: ['Finance', 'Technology'],
  },
};