import { FieldType } from '@/types/enums';

export const agentAdminCreationConfig = () => {
  return {
    sectionTitle: 'Agent Admin Creation',
    description: 'Fill in the details to create a new agent admin',
    steps: [
      'Basic Information',
      'Company Details',
      'Finance Details',
      'Documents',
      'Product Purpose',
      'Rate Margin',
      'Commission',
      'Corporate Onboarding',
    ],
    fields: {
      basicInformation: {
        vendorCode: {
          name: 'vendorCode',
          label: 'Vendor Code',
          type: FieldType.Text,
          placeholder: 'Enter Vendor Code',
        },
        fullName: {
          name: 'fullName',
          label: 'Full Name',
          type: FieldType.Text,
          required: true,
          placeholder: 'Enter Full Name',
        },
        emailId: {
          name: 'emailId',
          label: 'Email Id',
          type: FieldType.Email,
          required: true,
          placeholder: 'Enter Email Id',
        },
        phoneNo: {
          name: 'phoneNo',
          label: 'Phone No',
          type: FieldType.Phone,
          placeholder: 'Enter Phone No',
        },
        agentType: {
          name: 'agentType',
          label: 'Agent Type',
          type: FieldType.Select,
          options: [
            { value: 'type1', label: 'Type 1' },
            { value: 'type2', label: 'Type 2' },
          ],
          placeholder: 'Select Agent Type',
        },
        agentBranchCity: {
          name: 'agentBranchCity',
          label: 'Agent Branch City',
          type: FieldType.Text,
          placeholder: 'Enter Agent Branch City',
        },
        agentHOBranchState: {
          name: 'agentHOBranchState',
          label: 'Agent HO Branch State',
          type: FieldType.Text,
          placeholder: 'Enter Agent HO Branch State',
        },
        ebixRMName: {
          name: 'ebixRMName',
          label: 'Ebix RM Name',
          type: FieldType.Text,
          placeholder: 'Enter Ebix RM Name',
        },
        ebixRMBranchName: {
          name: 'ebixRMBranchName',
          label: 'Ebix RM Branch Name',
          type: FieldType.Text,
          placeholder: 'Enter Ebix RM Branch Name',
        },
        systemCode: {
          name: 'systemCode',
          label: 'System Code',
          type: FieldType.Text,
          placeholder: 'Enter System Code',
        },
        status: {
          name: 'status',
          label: 'Status',
          type: FieldType.Radio,
          required: true,
          options: {
            'Active': { label: 'Active', checked: true },
            'Inactive': { label: 'Inactive' }
          }
        },
        monthlyCreditLimit: {
          name: 'monthlyCreditLimit',
          label: 'Monthly Credit Limit (INR)',
          type: FieldType.Number,
          required: true,
          placeholder: 'Enter Monthly Credit Limit',
        },
        totalCreditDays: {
          name: 'totalCreditDays',
          label: 'Total Credit Days',
          type: FieldType.Number,
          required: true,
          placeholder: 'Enter Total Credit Days',
        },
      },
      companyDetails: {
        gstClassification: {
          name: 'gstClassification',
          label: 'GST Classification',
          type: FieldType.Select,
          required: true,
          options: [
            { value: 'regular', label: 'Regular' },
            { value: 'composition', label: 'Composition' },
          ],
          placeholder: 'Select GST Classification',
        },
        gstNumber: {
          name: 'gstNumber',
          label: 'GST Number',
          type: FieldType.Text,
          required: true,
          placeholder: 'Enter GST Number',
        },
        gstPhoneNo: {
          name: 'gstPhoneNo',
          label: 'Phone No',
          type: FieldType.Phone,
          placeholder: 'Enter Phone No',
        },
        flatDoorNumber: {
          name: 'flatDoorNumber',
          label: 'Flat/Door Number',
          type: FieldType.Text,
          placeholder: 'Enter Flat/Door Number',
        },
        roadStreet: {
          name: 'roadStreet',
          label: 'Road/Street',
          type: FieldType.Text,
          placeholder: 'Enter Road/Street',
        },
        areaLocality: {
          name: 'areaLocality',
          label: 'Area/Locality',
          type: FieldType.Text,
          placeholder: 'Enter Area/Locality',
        },
        gstCity: {
          name: 'gstCity',
          label: 'City',
          type: FieldType.Text,
          placeholder: 'Enter City',
        },
        gstState: {
          name: 'gstState',
          label: 'State',
          type: FieldType.Select,
          required: true,
          options: [
            { value: 'maharashtra', label: 'Maharashtra' },
            { value: 'karnataka', label: 'Karnataka' },
            // Add more states as needed
          ],
          placeholder: 'Select State',
        },
        pinCode: {
          name: 'pinCode',
          label: 'PIN Code',
          type: FieldType.Text,
          required: true,
          placeholder: 'Enter PIN Code',
        },
        gstBranch: {
          name: 'gstBranch',
          label: 'Branch',
          type: FieldType.Select,
          required: true,
          options: [
            { value: 'branch1', label: 'Branch 1' },
            { value: 'branch2', label: 'Branch 2' },
          ],
          placeholder: 'Select Branch',
        },
      },
      financeDetails: {
        financeSpocName: {
          name: 'financeSpocName',
          label: 'Financial SPOC Name',
          type: FieldType.Text,
          required: true,
          placeholder: 'Enter Financial SPOC Name',
        },
        financeSpocEmail: {
          name: 'financeSpocEmail',
          label: 'Finance SPOC Email',
          type: FieldType.Email,
          required: true,
          placeholder: 'Enter Finance SPOC Email',
        },
        financeSpocPhoneNo: {
          name: 'financeSpocPhoneNo',
          label: 'Finance SPOC Phone No',
          type: FieldType.Phone,
          required: true,
          placeholder: 'Enter Finance SPOC Phone No',
        },
      },
      documents: {
        agreementValid: {
          name: 'agreementValid',
          label: 'Valid',
          type: FieldType.Date,
          placeholder: 'Select Valid Date',
        },
        rbiLicenseCategory: {
          name: 'rbiLicenseCategory',
          label: 'RBI License Category',
          type: FieldType.Text,
          placeholder: 'Enter RBI License Category',
        },
        rbiLicenseValidity: {
          name: 'rbiLicenseValidity',
          label: 'RBI License Validity',
          type: FieldType.Date,
          placeholder: 'Select RBI License Validity',
        },
        noOfBranches: {
          name: 'noOfBranches',
          label: 'No. of Branches',
          type: FieldType.Number,
          placeholder: 'Enter No. of Branches',
        },
        extensionMonth: {
          name: 'extensionMonth',
          label: 'Extension Month',
          type: FieldType.Select,
          options: [
            { value: '1', label: 'January' },
            { value: '2', label: 'February' },
            { value: '3', label: 'March' },
            { value: '4', label: 'April' },
            { value: '5', label: 'May' },
            { value: '6', label: 'June' },
            { value: '7', label: 'July' },
            { value: '8', label: 'August' },
            { value: '9', label: 'September' },
            { value: '10', label: 'October' },
            { value: '11', label: 'November' },
            { value: '12', label: 'December' },
          ],
          placeholder: 'Select Extension Month',
        },
      },
      productPurpose: {},
      rateMargin: {},
      commission: {},
      corporateOnboarding: {},
    },
  };
};