export const transactionTableData = [
    {
      nium_order_id: "N-001",
      partner_order_id: "BMF-001",
      createdAt: "18.02.2025",
      customer_pan: "AFJPW0198D",
      transaction_type: "Card Load",
      // fxCurrency: "USD",
      // fxValue: "10,000.00",
      // fxRate: "85.20",
      // inrRate: "8,52,000.00",
      purpose_type: "BTQ",
      e_sign_status: "Success",
      v_kyc_status: "Success",
      incident_status: "Approved",
      merged_document:""
    },
    {
      nium_order_id: "N-002",
      partner_order_id: "BMF-002",
      createdAt: "10.02.2025",
      customer_pan: "AHURE123R",
      transaction_type: "Card Reload",
      fxCurrency: "EUR",
      // fxValue: "4,000.00",
      // fxRate: "109.10",
      // inrRate: "4,36,400.00",
      purpose_type: "BT",
      e_sign_status: "Pending",
      v_kyc_status: "Pending",
      incident_status: "Pending",
      merged_document:""
    },
    {
      nium_order_id: "N-003",
      partner_order_id: "BMF-003",
      createdAt: "05.01.2025",
      customer_pan: "AJYOI8986E",
      transaction_type: "Encashment",
      fxCurrency: "CAD",
      // fxValue: "2,000.00",
      // fxRate: "78.20",
      // inrRate: "1,56,400.00",
      purpose_type: "-",
      e_sign_status: "Expired",
      v_kyc_status: "Expired",
      incident_status: "Expired",
       merged_document:""
    },
    {
      nium_order_id: "N-004",
      partner_order_id: "BMF-004",
      createdAt: "28.12.2024",
      customer_pan: "BYUOW345T",
      transaction_type: "Remittance",
      fxCurrency: "USD",
      // fxValue: "40,000.00",
      // fxRate: "85.40",
      // inrRate: "34,16,000.00",
      purpose_type: "University Fee - Self Funded",
      e_sign_status: "Rejected",
      v_kyc_status: "Success",
      incident_status: "Pending",
       merged_document:""
    },
    {
      nium_order_id: "N-005",
      partner_order_id: "BMF-004",
      createdAt: "28.12.2024",
      customer_pan: "BYUOW345T",
      transaction_type: "Remittance",
      fxCurrency: "USD",
      // fxValue: "40,000.00",
      // fxRate: "85.40",
      // inrRate: "34,16,000.00",
      purpose_type: "University Fee - Self Funded",
      e_sign_status: "Rejected",
      v_kyc_status: "Success",
      incident_status: "Pending",
      merged_document:""
    }
    
  ];
  